config/routes.rb
Horarios::Application.routes.draw do
  resources :usuarios

  get "checkout/index"
  resources :trabajos

  root to: 'checkout#index', as: 'checkout'

  

end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
	validates :usuario, :tipo, :fecha, :hora, :usuario_id, presence: true
	validates :hora, format: {
		with: /[0-9]{2}:[0-9]{2}/,
		message: 'debe ser una hora valida (ej: 16:30, 09:25).'
	}
	validates :tipo, format: {
		with: /(entrada|salida)/,
		message: 'el tipo debe ser "entrada" o "salida"'
	}

	belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :id_usuario,  uniqueness: true
	validates :nombre, :clave, presence: true 
	validates :nombre, length: {minimum: 5, too_short: "el nombre debe tener al menos 5 caracteres"}
	validates :clave, length: {minimum: 5, too_short: "la clave debe tener al menos 5 caracteres"}

	has_many :trabajos, dependent: :destroy
	before_destroy :asegurarse_que_no_tiene_trabajos_asociados

	private
	
	def asegurarse_que_no_tiene_trabajos_asociados
		if trabajos.empty?
			return true
		else
			errors.add(:base, 'Trabajos asociados')
			return false
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

	def usuarioActual(nombre)
		

	end
		

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
	@trabajos = Trabajo.order(:fecha).order(:usuario)
  end
end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  before_action :set_trabajo, only: [:show, :edit, :update, :destroy]

  # GET /trabajos
  # GET /trabajos.json
  def index
    @trabajos = Trabajo.all
  end

  # GET /trabajos/1
  # GET /trabajos/1.json
  def show
  end

  # GET /trabajos/new
  def new
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
  end

  # POST /trabajos
  # POST /trabajos.json
  def create
    @trabajo = Trabajo.new(trabajo_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to @trabajo, notice: 'Trabajo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trabajo }
      else
        format.html { render action: 'new' }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajos/1
  # PATCH/PUT /trabajos/1.json
  def update
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to @trabajo, notice: 'Trabajo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajos/1
  # DELETE /trabajos/1.json
  def destroy
    @trabajo.destroy
    respond_to do |format|
      format.html { redirect_to trabajos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo = Trabajo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabajo_params
      params.require(:trabajo).permit(:usuario, :tipo, :fecha, :hora)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:id_usuario, :nombre, :clave)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/trabajos_helper.rb
module TrabajosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/checkout/index.html.erb
<h1>Checkout</h1>

<% @usuarioAnterior = -1 %>
<% @trabajos.each do |trabajo| %>
<div class="entry">
	<%if trabajo.usuario != @usuarioAnterior%>
		<h3><%= trabajo.usuario %></h3>
	<% end %>
	<div class="price_line">
		<span class="price"><%= trabajo.tipo %></span>
		<span class="price"><%= trabajo.fecha %></span>
		<span class="price"><%= trabajo.hora %></span>
	</div>
	<% @usuarioAnterior = trabajo.usuario %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Horarios</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trabajos/_form.html.erb
<%= form_for(@trabajo) do |f| %>
  <% if @trabajo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trabajo.errors.count, "error") %> prohibited this trabajo from being saved:</h2>

      <ul>
      <% @trabajo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.text_field :hora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trabajos/edit.html.erb
<h1>Editing trabajo</h1>

<%= render 'form' %>

<%= link_to 'Show', @trabajo %> |
<%= link_to 'Back', trabajos_path %>

app/views/trabajos/index.html.erb
<h1>Listing trabajos</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Tipo</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trabajos.each do |trabajo| %>
      <tr>
        <td><%= trabajo.usuario %></td>
        <td><%= trabajo.tipo %></td>
        <td><%= trabajo.fecha %></td>
        <td><%= trabajo.hora %></td>
        <td><%= link_to 'Show', trabajo %></td>
        <td><%= link_to 'Edit', edit_trabajo_path(trabajo) %></td>
        <td><%= link_to 'Destroy', trabajo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabajo', new_trabajo_path %>

app/views/trabajos/new.html.erb
<h1>New trabajo</h1>

<%= render 'form' %>

<%= link_to 'Back', trabajos_path %>

app/views/trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @trabajo.usuario %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @trabajo.tipo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @trabajo.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @trabajo.hora %>
</p>

<%= link_to 'Edit', edit_trabajo_path(@trabajo) %> |
<%= link_to 'Back', trabajos_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.number_field :id_usuario %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :clave %><br>
    <%= f.text_field :clave %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Clave</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.id %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.clave %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id usuario:</strong>
  <%= @usuario.id_usuario %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @usuario.clave %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>